org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512M
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.1+26.2
maven_group=github.mcdatapack.more_concretes
archives_base_name=more_concretes

# Dependencies
fabric_api_version=0.161.0+26.2